version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    # M1対応
    platform: linux/amd64
    container_name: godockerDB
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: godocker
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    healthcheck:
      test: mysqladmin -u docker -ppassword ping
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  db:
